### ISSUE TITLE
Ошибка сервера 429 (слишком много запросов за единицу времени)

### ISSUE THREAD

**Issue by wmakeev** [wmakeev/moysklad-client#20]
При большом количестве последовательных или параллельных запросов к REST API часто возникает ошибка `429 - The user has sent too many requests in a given amount of time`.  

Экспериментальным путем установлено, что сервис не позволяет выполнять более 2-х одновременных запросов и таймаут между запросами должен быть примерно не менее 250 ms.

Необходимо реализовать встроенную очередь запросов, которая будет учитывать описанные выше ограничения.

**Comment by alukos** [comment]
Поддержка MC ответила, что примерно две недели назад ввели дополнительные лимиты.

Александр Чепусенко Сегодня в 16:41
Здравствуйте.

В настоящий момент для запросов по REST API действуют следующие лимиты:
1) не более 1000 элементов в запросе;
2) не более 5 запросов в секунду от одного пользователя с одного IP-адреса;
3) не более 2 одновременных запросов от одного пользователя с одного IP-адреса;
4) не более 20 одновременных запросов с одного IP-адреса.

Обратите внимание, что одновременным запросом считается в том числе и тот, который отправляется при еще не полученном ответе на предыдущий запрос.

Изменение лимитов не производится

**Comment by wmakeev** [comment]
Спасибо, за информацию! Жалко что официально не публикуется. Проверю и приму в работу.

**Comment by wmakeev** [comment]
В целом проблема решена. Осталось подумать над тем как учесть случаи когда помимо одного клиента к серверу с текущего IP обращаются другие его экземпляры.
Скорее всего, когда поймана ошибка 429, нужно подождать некоторый случайный период времени и повторить запрос. Но это уже задача для следующих версий.

**Comment by p2rcoder** [comment]
какие на данный момент ограничения? где их посмотреть? через раз работает, ставлю задержку между запросами 5 секунд, обновляю цены, передаю в одном запросе 500 товаров, post запрос сюда https://online.moysklad.ru/api/remap/1.1/entity/product - 1 раз прошло нормально, потом начало выдавать 429 ошибку
