### ISSUE TITLE
Ошибка модели данных в версии 0.2.8

### ISSUE THREAD

**Issue by wmakeev** [wmakeev/moysklad-client#21]
Модель данных МойСклад преобразуется из xsd-модели во внутреннее представление автоматически, но в процессе трансформации применяется несколько заплаток с целью исправить некоторые неудобные моменты. В новой модели одна из таких заплаток сработала не корректно. Ошибка коснулась сущности `Good` (выпали некоторые поля, к примеру `buyPrice`).

Необходимо оптимизировать применение таких заплаток, чтобы избежать возможных ошибок в будущем.

**Comment by egorovcharenko** [comment]
У меня до сих пор не работает buyPrice

**Comment by wmakeev** [comment]
На ветке 0.2.9 должен работать. Я как понял, вы уже разобрались.
