### ISSUE TITLE
В node.js не работает пример из вики

### ISSUE THREAD

**Issue by zorgzerg** [wmakeev/moysklad-client#23]
Добрый день.
Хотел сегодня попробовать библиотеку, обломался на самом первом этапе. Пример для синхронной работы не работает, хотя в Google Script, к примеру все нормально, браузер по генерируемым ссылкам тоже корректно все отдает. 

Версия ноды v0.10.25
Версия библиотеки v0.2.8
Установлено из офф. репов и на на Ubuntu 14.04.3 LTS.

Используемый код: 
```javascript
var Sync = require('sync'),
    client = require('moysklad-client').createClient("login","password");

Sync(function () {

    var order = client.from('customerOrder')
        .sort('moment', 'desc')
        .first();

    console.log(order);
    return order.name;

}, function (err, data) {
    if (err) console.error(err);
    console.log(data);
});

```

Возвращает вот что:
```
# nodejs server.js 
moysklad-client info: moysklad-client v0.2.8 (index.js:12)
moysklad-client info: http GET https://online.moysklad.ru/exchange/rest/ms/xml/CustomerOrder/list/?sort=moment&sortMode=desc&count=1 (node.js:30)
null
[TypeError: Cannot read property 'name' of null]
undefined
moysklad-client info: http 200 https://online.moysklad.ru/exchange/rest/ms/xml/CustomerOrder/list/?sort=moment&sortMode=desc&count=1 116ms 1780b (node.js:49)
```

В чем может быть затык? И еще, я вижу, что библиотека пытается юзать REST сервис, а JSON API она еще не умеет?

**Comment by wmakeev** [comment]
Я недавно выпилил #19 из библиотеки зависимости необходимые для работы в синхронном режиме. Их необходимо установить вручную:
- `npm i common-node -save`
- `npm i node-fibers -save` (есть в зависимостях библиотеки `sync`, установливать нужно только если используете npm < 3.x)

В версии 0.2.8 есть небольшой баг с моделью данных #21 (имейте ввиду если захотите сохранять товары). Фикс будет опубликован в версии 0.2.9 (в работе).

Для JSON API будет другая библиотека с совершенно иной архитектурой (без поддержки синхронного режима). Подробности я ещё обдумываю. Просто перейти на JSON API сейчас не получится, он в целом не покрывает все возможности XML API. Придется делать некий гибрид.

**Comment by wmakeev** [comment]
Обновить документацию #24

**Comment by zorgzerg** [comment]
Да, я уже хлебнул горюшка с JSON API. Элементарно нельзя сделать выборку по дате обновления записи ( как говорится: будем подождать )
