### ISSUE TITLE
При обновлении на 0.2.8 перестало работать (относится к Meteor)

### ISSUE THREAD

**Issue by egorovcharenko** [wmakeev/moysklad-client#25]
Недавно обновил версию, теперь при попытке вызова любого метода - пишет:
`Cannot find module 'common-node/lib/httpclient'`

Может дело в метеоре - я к нему подключаю, не напрямую к Node.js, но версия 0.2.6 работала без проблем.

Update: пытался откататься обратно к 0.2.6, выдало целый фонтан ошибок:
`While building package npm-container:
error: couldn't install npm package moysklad-client@0.2.6: Command failed: npm http GET https://registry.npmjs.org/moysklad-client
npm http 304 https://registry.npmjs.org/moysklad-client
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/common-node
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/stampit
npm http GET https://registry.npmjs.org/tracer
npm http GET https://registry.npmjs.org/xmldom
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/moment
npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm http 304 https://registry.npmjs.org/xmldom
npm http 304 https://registry.npmjs.org/common-node
npm http 304 https://registry.npmjs.org/stampit
npm http 304 https://registry.npmjs.org/tracer
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/dateformat
npm http GET https://registry.npmjs.org/tinytim
npm http 304 https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/dateformat
npm http GET https://registry.npmjs.org/mout
npm http 304 https://registry.npmjs.org/mout
npm http 304 https://registry.npmjs.org/tinytim
npm http GET https://registry.npmjs.org/fibers
npm http 304 https://registry.npmjs.org/fibers
gypBuild failed
"nodejs" �� ����� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� �������� 䠩���.
npm ERR! Error: ENOENT, lstat 'C:\Meteor\zupjs-old\zupjs\packages\npm-container\.npm\package-new-149zeh4\node_modules\moysklad-client\node_modules\stampit\node_modules\mout\src\queryString\decode.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>`

и так еще два экрана.

**Comment by egorovcharenko** [comment]
Разобрался кажется, надо зависимость ставить так: 		

```
"dependencies": {
	"moysklad-client": "git://github.com/wmakeev/moysklad-client#0.2.9"
}
```

**Comment by wmakeev** [comment]
В master пока не залил, сам по тегу загружаю. Ваш коммент будет стимулом доделать )

**Comment by egorovcharenko** [comment]
Хорошо) Еще кстати если кто столкнулся - помогло обновление на метеор 1.3, недавно вышел.

**Comment by egorovcharenko** [comment]
Виталий, день добрый, подскажите пожалуйста, где-то неделю начала вылетать ошибка "Error: Unexpected element [overhead]" при загрузке отгрузок. Раньше такое было когда на версии 0.2.8 был, после обновления на 0.2.9 ушло, теперь опять вернулось. Вы ничего не меняли?

**Comment by wmakeev** [comment]
@egorovcharenko Нет. Это обновился XML в МойСклад. У меня та же ошибка. Сегодня надо обновить модель. Вечером должен успеть сделать.

**Comment by egorovcharenko** [comment]
Спасибо, буду ждать!

**Comment by wmakeev** [comment]
@egorovcharenko #29

**Comment by wmakeev** [comment]
Обновил модель и отключил логгер. Опубликовал версию 0.2.9 в npm.
