### ISSUE TITLE
Улучшение: иметь возможность отключать логирование вызовов сервисов МС

### ISSUE THREAD

**Issue by egorovcharenko** [wmakeev/moysklad-client#28]
Иначе при частых вызовах получается так: http://joxi.ru/823xPeRS6jw7oA

**Comment by wmakeev** [comment]
Согласен. Хотел сделать это в следующей версии. Но там я буду немного "ломать" интерфейс. Добавлю в этой.

**Comment by wmakeev** [comment]
Не получается в этой версии закончить всё по уму. Возможность опционального отключения логгера тянет за собой много изменений, которые требуют чуть иного интерфейса создания экземпляра клиента. А это уже обратно несовместимые изменения.

Поступил проще - просто пока вырезал код с логгером в версии 0.2.9.

**Comment by egorovcharenko** [comment]
Подтверждаю - логгирование убралось, спасибо!
