### ISSUE TITLE
Ошибка: Error: Can't sleep in node.js async env.

### ISSUE THREAD

**Issue by egorovcharenko** [wmakeev/moysklad-client#30]
Пока не понял, в какой момент получается (99% времени все нормально), но иногда появляется. Раньше не было.

Также, перед ней выскакивает другая ошибка: TypeError: Cannot read property 'headers' of undefined. Опять же, очень редко.

Такое ощущение, что при изменении атрибутов объекта.

**Comment by egorovcharenko** [comment]
Хотел добавить, что "редко" - имеется в виду относительно общего количества запросов, но в некоторых случаях она появляется в 100% случаев, что стопорит работу системы.

**Comment by wmakeev** [comment]
Без контекста, наверно будет сложно разобраться. Может есть возможность отправить код при выполнении которого выскакивает такая ошибка и стек этой ошибки?

**Comment by egorovcharenko** [comment]
Да, буду смотреть, сейчас вижу что возможно ошибка вообще не в модуле.

**Comment by egorovcharenko** [comment]
Ошибка выскакивает где-то здесь при вызове client.load:

```
Exception while invoking method 'executeOption' TypeError: Cannot read property 'headers' of undefined
I20160414-14:05:16.774(3)?     at Object.fetch.fetch (/var/www/meteor/zupjs/node_modules/moysklad-client/src/node_modules/project/fetch/common-node.js:74:38)
I20160414-14:05:16.774(3)?     at Object.fetch.fetch (/var/www/meteor/zupjs/node_modules/moysklad-client/src/node_modules/project/fetch/index.js:21:38)
I20160414-14:05:16.774(3)?     at Object.fetch (/var/www/meteor/zupjs/node_modules/moysklad-client/src/moysklad-client/rest-clients/ms-xml/methods/fetch.js:36:20)
I20160414-14:05:16.774(3)?     at Object.module.exports [as get] (/var/www/meteor/zupjs/node_modules/moysklad-client/src/moysklad-client/rest-clients/ms-xml/methods/get.js:27:10)
I20160414-14:05:16.774(3)?     at Object.load (/var/www/meteor/zupjs/node_modules/moysklad-client/src/moysklad-client/client/methods/load.js:71:21)
I20160414-14:05:16.774(3)?     at server/processes.coffee:159:34
I20160414-14:05:16.774(3)?     at Function._.each._.forEach (packages/underscore.js:142:22)
I20160414-14:05:16.774(3)?     at server/processes.coffee:55:15
I20160414-14:05:16.774(3)?     at Function._.each._.forEach (packages/underscore.js:142:22)
I20160414-14:05:16.775(3)?     at server/processes.coffee:52:11
```

**Comment by egorovcharenko** [comment]
И такое ощущение что после этого перестает работать клиент во всех случаях его вызова с этой же ошибкой.

**Comment by egorovcharenko** [comment]
Посмотрел еще, метод load вызывался с первым параметром "customerOrder", возможно ли что с маленькой буквы нельзя писать? Хотя в других местах пишу - вроде ок.

`order = client.load('customerOrder', entityUuid)`

**Comment by wmakeev** [comment]
@egorovcharenko Не имеет значение с большой или с маленькой. Тут дело в том, что код который должен выполнятся синхронно в Common Node, каким-то образом начинает выполнятся асинхронно. `Can't sleep in node.js async env.` - эта ошибка из модуля который должен работать только в node режиме. Как такое получается? Пока ломаю голову. Код никак не глянуть? Может через  TeamViewer?

**Comment by egorovcharenko** [comment]
Посмотреть конечно можно, можно хоть по скайпу - egor.ovcharenko.
Я честно говоря в Node.js особо не разбираюсь, но код выполняется в методе метеора, и он возможно выполняется асинхронно - опять же, в этом тоже не разбираюсь.
